"""Phase 0 generation entry points."""

from __future__ import annotations

import re
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class GeneratedArtifact:
    """Metadata for a generated module artifact."""

    module_name: str
    schema_path: Path
    output_path: Path


def _sanitize_identifier(name: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not cleaned:
        cleaned = "Schema"
    if cleaned[0].isdigit():
        cleaned = f"_{cleaned}"
    return cleaned


def _derive_module_name(schema_root: ET.Element, schema_path: Path) -> str:
    package_name = schema_root.attrib.get("package", "")
    if package_name:
        parts = [part for part in re.split(r"[^A-Za-z0-9]+", package_name) if part]
        if parts:
            return _sanitize_identifier("".join(p.capitalize() for p in parts))
    return _sanitize_identifier(schema_path.stem.capitalize())


def _load_schema_root(schema_path: Path) -> ET.Element:
    try:
        root = ET.parse(schema_path).getroot()
    except ET.ParseError as exc:
        raise ValueError(f"Invalid XML in schema {schema_path}: {exc}") from exc
    if not root.tag.endswith("messageSchema"):
        raise ValueError(f"Expected messageSchema root element, got {root.tag!r}")
    return root


def generate(
    schema_path: str | Path,
    output_dir: str | Path,
    module_name: str | None = None,
    validate: bool = True,
    warnings_fatal: bool = False,
    suppress_warnings: bool = False,
    overwrite: bool = False,
) -> GeneratedArtifact:
    """Generate a placeholder Python module from an SBE schema.

    This is a Phase 0 scaffold entry point. It validates basic schema shape and
    writes a deterministic placeholder module.
    """

    del validate, warnings_fatal, suppress_warnings

    schema = Path(schema_path)
    if not schema.is_file():
        raise FileNotFoundError(f"Schema file not found: {schema}")

    root = _load_schema_root(schema)
    if module_name:
        resolved_module_name = _sanitize_identifier(module_name)
    else:
        resolved_module_name = _derive_module_name(root, schema)

    output_base = Path(output_dir)
    output_base.mkdir(parents=True, exist_ok=True)
    output_path = output_base / f"{resolved_module_name}.py"
    if output_path.exists() and not overwrite:
        raise FileExistsError(
            f"Output file already exists: {output_path}. Pass overwrite=True to replace it."
        )

    module_text = f'''"""Generated by pysbe Phase 0 scaffold.

Schema: {schema}
Module: {resolved_module_name}
"""

from __future__ import annotations

SCHEMA_PATH = {str(schema)!r}
MODULE_NAME = {resolved_module_name!r}


def not_implemented() -> None:
    """Placeholder until IR/codegen phases are implemented."""
    raise NotImplementedError("pysbe code generation is not implemented yet")
'''
    output_path.write_text(module_text, encoding="utf-8")

    return GeneratedArtifact(
        module_name=resolved_module_name,
        schema_path=schema,
        output_path=output_path,
    )


def generate_ir_file(schema_path: str | Path) -> dict[str, Any]:
    """Return minimal schema metadata for Phase 0 CLI plumbing."""

    schema = Path(schema_path)
    if not schema.is_file():
        raise FileNotFoundError(f"Schema file not found: {schema}")

    root = _load_schema_root(schema)
    messages: list[str] = []
    for child in root:
        tag = child.tag.split("}")[-1]
        if tag == "message":
            name = child.attrib.get("name")
            if name:
                messages.append(name)

    return {
        "schema_path": str(schema),
        "package": root.attrib.get("package", ""),
        "id": int(root.attrib.get("id", "0")),
        "version": int(root.attrib.get("version", "0")),
        "byte_order": root.attrib.get("byteOrder", "littleEndian"),
        "messages": messages,
    }
